/**
 * Auto generated by Thrift2Ts.
 *
 * Sat Jun 24 2017 21:04:54 GMT+0800 (CST)
 */

import Request from "./request";

export interface SharedStruct {
    key: number;
    value: string;
}

export function getStruct(key: number): Promise<SharedStruct> {
    return Request<SharedStruct>("SharedService.getStruct", { key })
}


export default {
    getStruct
}
